name: Open URL on Successful Merge

on:
  pull_request:
    types:
      - closed

jobs:
  open-url:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Open URL on successful merge
      if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
      run: |
        # Add your logic to open the desired URL here
        echo "Opening URL after successful merge"
        # For example, you can use a tool like cURL or wget to make a request to the URL
        curl -L https://example.com
